# Generated by Django 5.2.8 on 2025-11-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heartbeat_date', models.DateTimeField(verbose_name='date of heartbeat signal arrival')),
                ('chip_id', models.IntegerField(verbose_name='unique chip id')),
            ],
        ),
    ]
