# Generated by Django 5.2.8 on 2025-11-15 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp_firmware_server_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_id', models.IntegerField(verbose_name='unique chip id')),
            ],
        ),
        migrations.CreateModel(
            name='HeartbeatSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heartbeat_date', models.DateTimeField(verbose_name='date of heartbeat signal arrival')),
                ('esp_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esp_firmware_server_app.espdevice')),
            ],
        ),
        migrations.DeleteModel(
            name='EspHeartbeat',
        ),
    ]
